# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dfevrier/Perso/appleseed-log-parser/appleseed_log_parser.ui'
#
# Created: Wed May 13 09:32:19 2015
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(739, 611)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox_3 = QtGui.QGroupBox(self.splitter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.recent_log_files_listWidget = QtGui.QListWidget(self.groupBox_3)
        self.recent_log_files_listWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.recent_log_files_listWidget.setObjectName("recent_log_files_listWidget")
        self.verticalLayout.addWidget(self.recent_log_files_listWidget)
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.log_tab = QtGui.QWidget()
        self.log_tab.setObjectName("log_tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.log_tab)
        self.verticalLayout_2.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.log_level_label = QtGui.QLabel(self.log_tab)
        self.log_level_label.setObjectName("log_level_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.log_level_label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.all_cb = QtGui.QCheckBox(self.log_tab)
        self.all_cb.setObjectName("all_cb")
        self.horizontalLayout_3.addWidget(self.all_cb)
        self.info_cb = QtGui.QCheckBox(self.log_tab)
        self.info_cb.setObjectName("info_cb")
        self.horizontalLayout_3.addWidget(self.info_cb)
        self.warning_cb = QtGui.QCheckBox(self.log_tab)
        self.warning_cb.setObjectName("warning_cb")
        self.horizontalLayout_3.addWidget(self.warning_cb)
        self.error_cb = QtGui.QCheckBox(self.log_tab)
        self.error_cb.setObjectName("error_cb")
        self.horizontalLayout_3.addWidget(self.error_cb)
        self.fatal_cb = QtGui.QCheckBox(self.log_tab)
        self.fatal_cb.setObjectName("fatal_cb")
        self.horizontalLayout_3.addWidget(self.fatal_cb)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_2 = QtGui.QLabel(self.log_tab)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.icon_cb = QtGui.QCheckBox(self.log_tab)
        self.icon_cb.setObjectName("icon_cb")
        self.horizontalLayout_4.addWidget(self.icon_cb)
        self.timestamp_cb = QtGui.QCheckBox(self.log_tab)
        self.timestamp_cb.setObjectName("timestamp_cb")
        self.horizontalLayout_4.addWidget(self.timestamp_cb)
        self.thread_id_cb = QtGui.QCheckBox(self.log_tab)
        self.thread_id_cb.setObjectName("thread_id_cb")
        self.horizontalLayout_4.addWidget(self.thread_id_cb)
        self.vm_cb = QtGui.QCheckBox(self.log_tab)
        self.vm_cb.setObjectName("vm_cb")
        self.horizontalLayout_4.addWidget(self.vm_cb)
        self.msg_cat_cb = QtGui.QCheckBox(self.log_tab)
        self.msg_cat_cb.setObjectName("msg_cat_cb")
        self.horizontalLayout_4.addWidget(self.msg_cat_cb)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.filter_label = QtGui.QLabel(self.log_tab)
        self.filter_label.setObjectName("filter_label")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.filter_label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filter_lineEdit = QtGui.QLineEdit(self.log_tab)
        self.filter_lineEdit.setObjectName("filter_lineEdit")
        self.horizontalLayout_2.addWidget(self.filter_lineEdit)
        self.clear_filter_button = QtGui.QPushButton(self.log_tab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_filter_button.setIcon(icon)
        self.clear_filter_button.setIconSize(QtCore.QSize(16, 16))
        self.clear_filter_button.setObjectName("clear_filter_button")
        self.horizontalLayout_2.addWidget(self.clear_filter_button)
        self.horizontalLayout_2.setStretch(0, 1)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.filtered_log_listWidget = QtGui.QListWidget(self.log_tab)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.filtered_log_listWidget.setFont(font)
        self.filtered_log_listWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.filtered_log_listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.filtered_log_listWidget.setObjectName("filtered_log_listWidget")
        self.verticalLayout_2.addWidget(self.filtered_log_listWidget)
        self.tabWidget.addTab(self.log_tab, "")
        self.options_tab = QtGui.QWidget()
        self.options_tab.setObjectName("options_tab")
        self.frame_setting_groupBox = QtGui.QGroupBox(self.options_tab)
        self.frame_setting_groupBox.setGeometry(QtCore.QRect(30, 60, 231, 251))
        self.frame_setting_groupBox.setObjectName("frame_setting_groupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_setting_groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_setting_formLayout = QtGui.QFormLayout()
        self.frame_setting_formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.frame_setting_formLayout.setObjectName("frame_setting_formLayout")
        self.frame_setting_resolution_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_resolution_label.setObjectName("frame_setting_resolution_label")
        self.frame_setting_formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.frame_setting_resolution_label)
        self.frame_setting_resolution_value_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_resolution_value_label.setObjectName("frame_setting_resolution_value_label")
        self.frame_setting_formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.frame_setting_resolution_value_label)
        self.frame_setting_tile_size_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_tile_size_label.setObjectName("frame_setting_tile_size_label")
        self.frame_setting_formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.frame_setting_tile_size_label)
        self.frame_setting_tile_size_value_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_tile_size_value_label.setObjectName("frame_setting_tile_size_value_label")
        self.frame_setting_formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.frame_setting_tile_size_value_label)
        self.frame_setting_filter_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_filter_label.setObjectName("frame_setting_filter_label")
        self.frame_setting_formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.frame_setting_filter_label)
        self.frame_setting_filter_value_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_filter_value_label.setObjectName("frame_setting_filter_value_label")
        self.frame_setting_formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.frame_setting_filter_value_label)
        self.frame_setting_filter_size_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_filter_size_label.setObjectName("frame_setting_filter_size_label")
        self.frame_setting_formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.frame_setting_filter_size_label)
        self.frame_setting_filter_size_value_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_filter_size_value_label.setObjectName("frame_setting_filter_size_value_label")
        self.frame_setting_formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.frame_setting_filter_size_value_label)
        self.frame_setting_color_space_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_color_space_label.setObjectName("frame_setting_color_space_label")
        self.frame_setting_formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.frame_setting_color_space_label)
        self.frame_setting_color_space_value_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_color_space_value_label.setObjectName("frame_setting_color_space_value_label")
        self.frame_setting_formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.frame_setting_color_space_value_label)
        self.frame_setting_premult_alpha_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_premult_alpha_label.setObjectName("frame_setting_premult_alpha_label")
        self.frame_setting_formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.frame_setting_premult_alpha_label)
        self.frame_setting_premult_alpha_value_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_premult_alpha_value_label.setObjectName("frame_setting_premult_alpha_value_label")
        self.frame_setting_formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.frame_setting_premult_alpha_value_label)
        self.frame_setting_clamping_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_clamping_label.setObjectName("frame_setting_clamping_label")
        self.frame_setting_formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.frame_setting_clamping_label)
        self.frame_setting_clamping_value_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_clamping_value_label.setObjectName("frame_setting_clamping_value_label")
        self.frame_setting_formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.frame_setting_clamping_value_label)
        self.frame_setting_gamma_correction_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_gamma_correction_label.setObjectName("frame_setting_gamma_correction_label")
        self.frame_setting_formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.frame_setting_gamma_correction_label)
        self.frame_setting_gamma_correction_value_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_gamma_correction_value_label.setObjectName("frame_setting_gamma_correction_value_label")
        self.frame_setting_formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.frame_setting_gamma_correction_value_label)
        self.frame_setting_crop_window_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_crop_window_label.setObjectName("frame_setting_crop_window_label")
        self.frame_setting_formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.frame_setting_crop_window_label)
        self.frame_setting_crop_window_value_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_crop_window_value_label.setObjectName("frame_setting_crop_window_value_label")
        self.frame_setting_formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.frame_setting_crop_window_value_label)
        self.frame_setting_pixel_format_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_pixel_format_label.setObjectName("frame_setting_pixel_format_label")
        self.frame_setting_formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.frame_setting_pixel_format_label)
        self.frame_setting_pixel_format_value_label = QtGui.QLabel(self.frame_setting_groupBox)
        self.frame_setting_pixel_format_value_label.setObjectName("frame_setting_pixel_format_value_label")
        self.frame_setting_formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.frame_setting_pixel_format_value_label)
        self.verticalLayout_3.addLayout(self.frame_setting_formLayout)
        self.tabWidget.addTab(self.options_tab, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.graph_tab = QtGui.QWidget()
        self.graph_tab.setObjectName("graph_tab")
        self.tabWidget.addTab(self.graph_tab, "")
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 739, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open_log_file = QtGui.QAction(MainWindow)
        self.action_Open_log_file.setIcon(icon)
        self.action_Open_log_file.setObjectName("action_Open_log_file")
        self.action_About_Appleseed = QtGui.QAction(MainWindow)
        self.action_About_Appleseed.setObjectName("action_About_Appleseed")
        self.action_About_Appleseed_Log_Parser = QtGui.QAction(MainWindow)
        self.action_About_Appleseed_Log_Parser.setIcon(icon)
        self.action_About_Appleseed_Log_Parser.setObjectName("action_About_Appleseed_Log_Parser")
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setIcon(icon)
        self.action_Quit.setObjectName("action_Quit")
        self.menuFile.addAction(self.action_Open_log_file)
        self.menuFile.addAction(self.action_Quit)
        self.menuHelp.addAction(self.action_About_Appleseed)
        self.menuHelp.addAction(self.action_About_Appleseed_Log_Parser)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Appleseed Log Parser", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Recents", None, QtGui.QApplication.UnicodeUTF8))
        self.log_level_label.setStatusTip(QtGui.QApplication.translate("MainWindow", "Display or hide the log\'s lines depending on its level.", None, QtGui.QApplication.UnicodeUTF8))
        self.log_level_label.setText(QtGui.QApplication.translate("MainWindow", "Log level:", None, QtGui.QApplication.UnicodeUTF8))
        self.all_cb.setText(QtGui.QApplication.translate("MainWindow", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.info_cb.setText(QtGui.QApplication.translate("MainWindow", "info", None, QtGui.QApplication.UnicodeUTF8))
        self.warning_cb.setText(QtGui.QApplication.translate("MainWindow", "warning", None, QtGui.QApplication.UnicodeUTF8))
        self.error_cb.setText(QtGui.QApplication.translate("MainWindow", "error", None, QtGui.QApplication.UnicodeUTF8))
        self.fatal_cb.setText(QtGui.QApplication.translate("MainWindow", "fatal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Line prefix:", None, QtGui.QApplication.UnicodeUTF8))
        self.icon_cb.setText(QtGui.QApplication.translate("MainWindow", "Icon", None, QtGui.QApplication.UnicodeUTF8))
        self.timestamp_cb.setText(QtGui.QApplication.translate("MainWindow", "Timestamp", None, QtGui.QApplication.UnicodeUTF8))
        self.thread_id_cb.setText(QtGui.QApplication.translate("MainWindow", "Thead ID", None, QtGui.QApplication.UnicodeUTF8))
        self.vm_cb.setText(QtGui.QApplication.translate("MainWindow", "Virtual Memory", None, QtGui.QApplication.UnicodeUTF8))
        self.msg_cat_cb.setText(QtGui.QApplication.translate("MainWindow", "Message category", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_label.setText(QtGui.QApplication.translate("MainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_filter_button.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log_tab), QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Frame settings", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_resolution_label.setText(QtGui.QApplication.translate("MainWindow", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_resolution_value_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_tile_size_label.setText(QtGui.QApplication.translate("MainWindow", "Tile size", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_tile_size_value_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_filter_label.setText(QtGui.QApplication.translate("MainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_filter_value_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_filter_size_label.setText(QtGui.QApplication.translate("MainWindow", "Filter size", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_filter_size_value_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_color_space_label.setText(QtGui.QApplication.translate("MainWindow", "Color space", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_color_space_value_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_premult_alpha_label.setText(QtGui.QApplication.translate("MainWindow", "Premult. alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_premult_alpha_value_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_clamping_label.setText(QtGui.QApplication.translate("MainWindow", "Clamping", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_clamping_value_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_gamma_correction_label.setText(QtGui.QApplication.translate("MainWindow", "Gamma correction", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_gamma_correction_value_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_crop_window_label.setText(QtGui.QApplication.translate("MainWindow", "Crop window", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_crop_window_value_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_pixel_format_label.setText(QtGui.QApplication.translate("MainWindow", "Pixel format", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_setting_pixel_format_value_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.options_tab), QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.graph_tab), QtGui.QApplication.translate("MainWindow", "Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open_log_file.setText(QtGui.QApplication.translate("MainWindow", "Open log file...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open_log_file.setToolTip(QtGui.QApplication.translate("MainWindow", "Open an Appleseed log file", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open_log_file.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About_Appleseed.setText(QtGui.QApplication.translate("MainWindow", "About Appleseed", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About_Appleseed_Log_Parser.setText(QtGui.QApplication.translate("MainWindow", "About Appleseed Log Parser", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

